import { ProductsService } from './products.service';
import { CreateProductDto } from './dto/create-product.dto';
import { UpdateProductDto } from './dto/update-product.dto';
export declare class ProductsController {
    private readonly productsService;
    constructor(productsService: ProductsService);
    create(createProductDto: CreateProductDto): Promise<import("./entities/product.entity").Product>;
    findAll(isActive?: string): Promise<import("./entities/product.entity").Product[]>;
    findOne(id: number): Promise<import("./entities/product.entity").Product>;
    getInventorySummary(): Promise<{
        totalValue: number;
        productsPerCategory: any[];
        totalProducts: number;
        totalStock: number;
    }>;
    update(id: number, updateProductDto: UpdateProductDto): Promise<import("./entities/product.entity").Product>;
    remove(id: number): Promise<{
        isActive: boolean;
        id: number;
        nombre: string;
        codigo: string;
        modelo: string;
        serie: string;
        categoria: string;
        precio: number;
        stock: number;
        stockMinimo: number;
        imagen: string;
        almacen: string;
        pasillo: string;
        fila: string;
        ubicacion: string;
        unidadMedida: string;
        movimientoInventario: string;
        descripcion: string;
        nota: string;
        camposPersonalizados: any[];
        vendidos: number;
        countItems: import("../inventory-counts/entities/count-item.entity").CountItem[];
        proveedorId: number;
        proveedor: import("../providers/entities/provider.entity").Provider;
        warehouseStocks: import("./entities/product-warehouse-stock.entity").ProductWarehouseStock[];
        isComodato: boolean;
        isSerialized: boolean;
        seriales: import("./entities/product-serial.entity").ProductSerial[];
        createdAt: Date;
        updatedAt: Date;
    }>;
    restore(id: number): Promise<import("./entities/product.entity").Product>;
}
