server {
    listen 80;
    # El server_name aquí es solo para Nginx, Traefik manejará el dominio real
    server_name localhost;

    # Ruta donde Nginx buscará los archivos estáticos
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Configuración para Single Page Applications (SPA)
    # Si una ruta no coincide con un archivo estático, Nginx servirá index.html
    # Esto permite que el enrutador de React maneje la URL
    location / {
        try_files $uri $uri/ /index.html;
    }
}